name: 'atmosync'
version: '1.0.0'
config-version: 2

profile: 'atmosync'

model-paths: ["models"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  atmosync:
    staging:
      +materialized: view
    marts:
      +materialized: table
